<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <RootNamespace>QuickClassMap.VS</RootNamespace>

    <!-- VSIX settings -->
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickClassMap.Core\QuickClassMap.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
    <VSCTCompile Include="QuickClassMap.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
    <None Update="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
    <Content Include="Resources\Logo.png">
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\LogoLarge.png" />
    <Content Include="Resources\NewClassDiagram.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.LanguageServices" Version="4.11.0" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.9.820" />
  </ItemGroup>
</Project>
